In [16]:
import numpy as np
import pandas as pd

In [28]:
# ### run 7
# det = np.array([1,2,3,6,7,9,10,11,13,15,17,18,19,20,25,26,28])
# ph_1779 = np.array([1685,1896,1552,1798,2057,1951,1740,1935,1236,1738,1754,1835,1935,1742,1700,1907,1419])
# ph_7724 = np.array([7319,8232,6744,7808,8938,8470,7556,8404,5370,7540,7617,7971,8402,7562,7385,8283,6162])



det = np.array([1,2,3,6,7,9,10,11,13,15,17,18,19,20,25,26])
ph_511 = np.array([])
ph_1368 = np.array([])

In [29]:
slope = (7724-1779)/(ph_7724-ph_1779)
slope

array([1.05520057, 0.93828914, 1.14503082, 0.98918469, 0.86397326,
       0.91194969, 1.02218019, 0.9189983 , 1.4380745 , 1.02464667,
       1.01398601, 0.96887223, 0.91928251, 1.02147766, 1.04573439,
       0.93240276, 1.2534261 ])

In [30]:
offset = 1779 - slope * ph_1779
offset

array([ 0.98704295,  0.00378788,  1.91217257,  0.44592346,  1.8070048 ,
       -0.21383648,  0.40646492,  0.73829031,  1.53991292, -1.83591865,
        0.46853147,  1.11945893,  0.18834081, -0.41408935,  1.25153914,
        0.90793601,  0.3883618 ])

In [31]:
calib_dict = {"det":det, "slope":slope, "offset":offset}

In [32]:
df  = pd.DataFrame(calib_dict)
df

    det     slope    offset
0     1  1.055201  0.987043
1     2  0.938289  0.003788
2     3  1.145031  1.912173
3     6  0.989185  0.445923
4     7  0.863973  1.807005
5     9  0.911950 -0.213836
6    10  1.022180  0.406465
7    11  0.918998  0.738290
8    13  1.438075  1.539913
9    15  1.024647 -1.835919
10   17  1.013986  0.468531
11   18  0.968872  1.119459
12   19  0.919283  0.188341
13   20  1.021478 -0.414089
14   25  1.045734  1.251539
15   26  0.932403  0.907936
16   28  1.253426  0.388362

In [33]:
df.to_csv("../calib/calib_2023apr.csv",index=False)

In [67]:
det = np.array([1,2,3,6,7,9,10,11,13,15,17,18,19,20,25,26])
ph_511 = np.array([483,543,445,516,593,559,498,555,354,498,503,526,555,499,487,547])
ph_1368 = np.array([1296,1459,1194,1383,1582,1500,1338,1489,951,1336,1349,1412,1488,1339,1310,1468])
ph_2754 = np.array([2609,2936,2403,2783,3184,3020,2695,2997,1915,2690,2715,2843,2995,2697,2636,2954])

# df = pd.DataFrame({"det":det,"ph_511":ph_511,"ph_1368":ph_1368,"ph_2754":ph_2754})
# df

slope = []
offset=[]
for i in range(len(det)):
    poly = np.polynomial.Polynomial.fit([ph_511[i],ph_1368[i],ph_2754[i]],[511,1368,2754],deg = 1)
    # res = np.polynomial.Polynomial.fit(np.array([0,1]),np.array([0,1]),deg = 1)
    slope.append(poly.convert().coef[1])
    offset.append(poly.convert().coef[0])
    

df_results = pd.DataFrame({"det":det,"slope":slope,"offset":offset})
df_results

    det     slope    offset
0     1  1.055087  1.093275
1     2  0.937419  1.342199
2     3  1.145637  0.778467
3     6  0.989469  0.101918
4     7  0.865639 -1.986654
5     9  0.911458  1.234175
6    10  1.020979  2.314956
7    11  0.918565  0.837344
8    13  1.436981  1.973564
9    15  1.023301  1.194854
10   17  1.014074  0.574629
11   18  0.968109  1.490497
12   19  0.919305  0.514328
13   20  1.020487  1.697129
14   25  1.043884  1.820999
15   26  0.931945  0.721652

In [68]:
df_results.to_csv("../calib/calib_2023apr.csv",index=False)