In [1]:
import numpy as np
import pandas as pd

In [2]:
det = np.array([1,2,3,4,5,6,7,9,10,11,13,15,18,19,20,25,26,27,28])

ph_511  = np.array([483,152,151,487,500,513,504,497,503,502,509,508,497,520,498,484,553,477,504])
ph_1779 = np.array([1682,531,526,1697,1743,1789,1755,1731,1753,1748,1775,1770,1743,1813,1742,1697,1928,1765,1758])
ph_7724 = np.array([7307,2308,2286,7368,7572,7773,7627,7518,7614,7595,7712,7690,7572,7880,7568,7373,8375,7649,7630])


# df = pd.DataFrame({"det":det,"ph_511":ph_511,"ph_1368":ph_1368,"ph_2754":ph_2754})
# df

slope = []
offset=[]
for i in range(len(det)):
    poly = np.polynomial.Polynomial.fit([ph_511[i],ph_1779[i],ph_7724[i]],[511,1779,7724],deg = 1)
    # poly = np.polynomial.Polynomial.fit([ph_511[i],ph_9034[i]],[511,9034],deg = 1)
    # res = np.polynomial.Polynomial.fit(np.array([0,1]),np.array([0,1]),deg = 1)
    slope.append(poly.convert().coef[1])
    offset.append(poly.convert().coef[0])
    

df_results = pd.DataFrame({"det":det,"slope":slope,"offset":offset})
df_results

    det     slope     offset
0     1  1.056968   0.798150
1     2  3.345541   2.495919
2     3  3.378263   1.402695
3     4  1.048270   0.308976
4     5  1.019926   1.141677
5     6  0.993513   1.453653
6     7  1.012572   1.239132
7     9  1.027333   0.538197
8    10  1.014340   0.820610
9    11  1.016869   0.975247
10   13  1.001376   1.416666
11   15  1.004287   1.088529
12   18  1.019629   3.134543
13   19  0.979985   1.805519
14   20  1.020289   2.336556
15   25  1.047144   3.194757
16   26  0.922140   1.082483
17   27  1.007150  17.425232
18   28  1.012278   0.180444

In [3]:
df_results.to_csv("../calib/calib_2024mar.csv",index=False)